### PR TITLE
#16: Crawling used wrong java language level

### LINKED ISSUE #16: Crawling used wrong java language level
For projects that use new Java features like try-with-resources, crawling fails with:
```
Variable resource not allowed here for source level below 9 at /home/jakob/exasol/project-keeper-maven-plugin/src/main/java/com/exasol/projectkeeper/validators/files/ProjectFilesValidator.java:69
```

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #16

### CODE REVIEW

File: src/main/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojo.java [hunk 1]
```diff
@@ -42,6 +44,23 @@ public void execute() throws MojoExecutionException, MojoFailureException {
         log.info("Found " + crawlResult.getErrorMessageDeclarations().size() + " valid error message declarations.");
     }
 
+    private int getJavaLanguageLevel() {
```
Comment (chiaradiamarcelo) [inline src/main/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojo.java:47]: Somehow it got me a bit confused to understand what "JavaLanguageLevel" meant.
Perhaps we can change to "JavaMajorRelease", or "JavaVersion" or something related?

**Review by chiaradiamarcelo — APPROVED** [review]
