### PR TITLE
#99: Use complete path for source files

### LINKED ISSUE #99: Use complete path for source files
When crawling multi-maven projects and aggregating the error reports, the crawler writes an invalid source path to the report:

Example:
* Error code: https://error-catalog.exasol.com/error-codes/e-pk-core-101.html
* Path: src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java
* Broken link: https://github.com/exasol/project-keeper/blob/3.0.0/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java#L375
* Correct link: https://github.com/exasol/project-keeper/blob/3.0.0/project-keeper/src/main/java/com/exasol/projectkeeper/validators/pom/PomFileValidator.java

The link must contain the project internal path to the maven module.

# Task
Fix the `aggregate` or `verify` task to use source paths including the path to the maven module.

### PR DESCRIPTION
**Pull request by skyglass**
closes #99 
Fixed source file complete path by adding sub-project prefix for multi-module projects

### CODE REVIEW

File: src/test/java/com/exasol/errorcodecrawlermavenplugin/crawler/ErrorMessageDeclarationCrawlerTest.java
Comment (kaklakariada) [inline src/test/java/com/exasol/errorcodecrawlermavenplugin/crawler/ErrorMessageDeclarationCrawlerTest.java:1]: Add a test where rootProjectDir is different and verify generated path.

**Review by kaklakariada — CHANGES_REQUESTED** [review]
Looks good! Please add integration test and a changelog entry

File: src/main/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojo.java [hunk 1]
```diff
@@ -57,7 +58,9 @@ public class ErrorCodeCrawlerMojo extends AbstractMojo {
     // [impl->dsn~src-directory-override]
     private List<Path> getSourcePaths() {
         if (this.sourcePaths == null || this.sourcePaths.isEmpty()) {
-            return List.of(Path.of("src/main/java"));
+            final var projectDir = this.project.getBasedir().toPath();
+            final var rootProjectDir = this.project.getParent() == null ? projectDir : this.project.getParent().getBasedir().toPath();
+            return List.of(Path.of(rootProjectDir.relativize(projectDir).toString(), "src", "main", "java"));
```
Comment (kaklakariada) [inline src/main/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojo.java:63]: Is it necessary to use the root project dir also here? I think we only need it in the `execute()` method.

File: src/main/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojo.java [hunk 2]
```diff
@@ -90,10 +93,11 @@ protected boolean isEnabled() {
     public void execute() throws MojoFailureException {
         if (isEnabled()) {
             final var projectDir = this.project.getBasedir().toPath();
+            final var rootProjectDir = this.project.getParent() == null ? projectDir : projectDir.getParent();
```
Comment (kaklakariada) [inline src/main/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojo.java:96]: Please extract this into a method

File: src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java [hunk 3]
```diff
@@ -73,6 +75,28 @@ void testErrorReport() throws VerificationException, IOException {
...
+
+        final ErrorCodeReport report = new ErrorCodeReportReader().readReport(verifier.getSubProjectErrorCodeReportPath());
+        final ErrorMessageDeclaration firstDeclaration = report.getErrorMessageDeclarations().get(0);
+        assertAll(//
+                () -> assertThat(report.getProjectName(), equalTo("sub-project")),
+                () -> assertThat(report.getProjectVersion(), equalTo("1.0.0")),
+                () -> assertThat(firstDeclaration.getIdentifier(), equalTo("E-TEST-1")),
+                () -> assertThat(firstDeclaration.getMessage(), equalTo("Test message")),
+                () -> assertThat(firstDeclaration.getSourceFile(), equalTo(path)),
+                () -> assertThat(firstDeclaration.getLine(), equalTo(10))//
```
Comment (kaklakariada) [inline src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java:96]: 👍

File: src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java [hunk 4]
```diff
@@ -216,6 +253,59 @@ static class ITVerifier {
                 throw new IllegalStateException("Failed to create test projects src folder.");
             }
             withConfiguration("testProject/" + CONFIG_NAME);
+            if (withSubProject) {
+                withSubProject();
+            }
```
Comment (kaklakariada) [inline src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java:258]: 👍

File: src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java [hunk 5]
```diff
@@ -73,6 +75,28 @@ void testErrorReport() throws VerificationException, IOException {
                                 + "\"sourceLine\":10,\"mitigations\":[]}]}"));
     }
 
+    @Test
+    void testSubProjectErrorReport() throws VerificationException, IOException, ErrorCodeReportReader.ReadException {
+        final String path = Path.of("sub-project/src/main/java/com/exasol/errorcodecrawlermavenplugin/examples/Test1.java")
```
Comment (kaklakariada) [inline src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java:80]: Rename to `exepectedPath`

File: src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java [hunk 6]
```diff
@@ -216,6 +253,59 @@ static class ITVerifier {
...
+            if (withSubProject) {
+                withSubProject();
+            }
+        }
+
+        ITVerifier withSubProject() throws IOException {
+            this.subProjectDir = this.projectDir.resolve("sub-project");
+            if (!(this.subProjectDir.toFile().mkdirs())) {
+                throw new IllegalStateException("Failed to create sub-project folder");
+            }
```
Comment (kaklakariada) [inline src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java:265]: When you use [Files.createDirectories()](https://docs.oracle.com/en%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2F%2F/java.base/java/nio/file/Files.html#createDirectories(java.nio.file.Path,java.nio.file.attribute.FileAttribute...))
* you don't need to check the return value
* you can directly use `Path` and don't need to convert it to `File`

File: src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java [hunk 7]
```diff
@@ -216,6 +253,59 @@ static class ITVerifier {
...
+            this.subProjectMainSrcJava = this.subProjectDir.resolve(Path.of("src", "main", "java"));
+            this.subProjectMainSrcPackage = this.subProjectMainSrcJava
+                    .resolve(Path.of("com", "exasol", "errorcodecrawlermavenplugin", "examples"));
+            this.subProjectTestSrcPackage = this.subProjectDir.resolve(
+                    Path.of("src", "test", "java", "com", "exasol", "errorcodecrawlermavenplugin", "examples"));
+            if (!(this.subProjectMainSrcPackage.toFile().mkdirs() && this.subProjectTestSrcPackage.toFile().mkdirs())) {
+                throw new IllegalStateException("Failed to create test sub projects src folder.");
+            }
```
Comment (kaklakariada) [inline src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java:273]: Same here: use [Files.createDirectories()](https://docs.oracle.com/en%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2F%2F/java.base/java/nio/file/Files.html#createDirectories(java.nio.file.Path,java.nio.file.attribute.FileAttribute...))

File: src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java [hunk 8]
```diff
@@ -216,6 +253,59 @@ static class ITVerifier {
...
+                withSubProject();
+            }
+        }
+
+        ITVerifier withSubProject() throws IOException {
+            this.subProjectDir = this.projectDir.resolve("sub-project");
+            if (!(this.subProjectDir.toFile().mkdirs())) {
+                throw new IllegalStateException("Failed to create sub-project folder");
+            }
+            this.subProjectMainSrcJava = this.subProjectDir.resolve(Path.of("src", "main", "java"));
```
Comment (kaklakariada) [inline src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java:266]:
```suggestion
            this.subProjectMainSrcJava = this.subProjectDir.resolve("src/main/java");
```
You can simplify this code, same below.

File: src/test/java/com/exasol/errorcodecrawlermavenplugin/crawler/ErrorMessageDeclarationCrawlerTest.java [hunk 9]
```diff
@@ -45,6 +54,31 @@ void testCrawlValidCode() {
...
+    void testSubProjectCrawlValidCode() throws IOException {
+        Path subProjectDir = projectDir.resolve("sub-project");
+        Path subProjectTestSrcJava = subProjectDir.resolve(Path.of("src", "test", "java"));
+        Path subProjectTestSrcPackage = subProjectTestSrcJava
+                .resolve(Path.of("com", "exasol", "errorcodecrawlermavenplugin", "examples"));
+        subProjectTestSrcPackage.toFile().mkdirs();
+        ErrorMessageDeclarationCrawler subProjectDeclarationCrawler = new ErrorMessageDeclarationCrawler(
+                subProjectDir.getParent(), subProjectDir, emptyList(), 11, Collections.emptyList());
+        Files.copy(Path.of(TEST_DIR).resolve("Test1.java"), subProjectTestSrcPackage.resolve("Test1.java"), StandardCopyOption.REPLACE_EXISTING);
+        final Path path = projectDir.relativize(subProjectTestSrcPackage.resolve("Test1.java"));
```
Comment (kaklakariada) [inline src/test/java/com/exasol/errorcodecrawlermavenplugin/crawler/ErrorMessageDeclarationCrawlerTest.java:67]: Rename to `expectedPath`. Also better define the path without using `relativize` to make it clear which path is expected.

**Review by kaklakariada — CHANGES_REQUESTED** [review]

File: src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java (hunk 8 above)
Comment (skyglass) [reply src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java:266]: In general, different operating systems might use different file and path separators. You can see some examples here: https://www.baeldung.com/java-file-vs-file-path-separator
So, in general, it is safer to pass a list of path directories and let Path class take care about adding File or Path separator, correspondent to current operating system. Path class will use File.pathSeparator instead of hardcoding "/".

Comment (skyglass) [reply src/test/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojoIT.java:266]: Actually, if it is the code in the test, then I think it is ok to hardcode file separator as "/".
In case it will ever cause the issue with unit tests on some operating systems, then maybe we might reconsider this approach. But for now, I think it is ok to hardcode "/" in the tests.

File: src/main/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojo.java (hunk 1 above)
Comment (skyglass) [reply src/main/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojo.java]: Yes, the original code used Path.of("src/main/java"), which was not correct for sub-projects. So, in order to fix the bug, we should also fix the code here.
I have improved the code a little bit, by passing projectDir and rootProjectDir as parameters from execute method.

Comment (skyglass) [reply src/main/java/com/exasol/errorcodecrawlermavenplugin/ErrorCodeCrawlerMojo.java]: Instead of rootProjectDir.relativize(projectDir) we might also use projectDir.getFile().getName + "/src/main/java", but in general, it will not work for nested sub-projects with nesting level more than one. So I think rootProjectDir.relativize(projectDir) is generally safer to use.

**Review by kaklakariada — DISMISSED** [review]

**Review by kaklakariada — APPROVED** [review]
